### ISSUE TITLE
2 zone example for Supermicro X9/X10/X11 boards

### ISSUE THREAD

**Issue by rajil** [chenxiaolong/ipmi-fan-control#37]
I would appreciate an example for a two zone system. This is common for Supermicro X9/X10/X11 as described [here](https://forums.servethehome.com/index.php?resources/supermicro-x9-x10-x11-fan-speed-control.20/).

In my case I have Zone 0 has the CPU/Rear case fans; and Zone 1 has the front rack case fans for HDD. I am note sure what to put in the file. For instance, whether i need two step definitions or not. I was previously using IPMIFanControl.pl and could see what it is doing in the its log. This program does not output much of a log.

The config i used is listed below. Is this correct?

```
[[zones]]
ipmi_zones = [0]
interval = 5
sources = [
    { type = "ipmi", sensor = "CPU1 Temp" },
    { type = "ipmi", sensor = "CPU2 Temp" },
    { type = "file", path = "/sys/class/thermal/thermal_zone0/temp" },
]
steps = [
    { temp = 30, dcycle = 30 },
    { temp = 70, dcycle = 70 },
]
[[zones]]
ipmi_zones = [1]
interval = 5
sources = [
    { type = "smart", block_dev = "/dev/disk/by-id/disk1" },
    { type = "smart", block_dev = "/dev/disk/by-id/disk2" },
]
aggregation = { type = "average" }
steps = [
    { temp = 30, dcycle = 30 },
    { temp = 70, dcycle = 70 },
]
[sessions]
```

**Comment by chenxiaolong** [comment]
Yep, what you have should be correct. With the config you posted:

For zone 1, it'll use the maximum temperature of `CPU1 Temp`, `CPU2 Temp`, and `thermal_zone0` to determine the fan speed. The fan speed is set to 30% if the temperature is <= 30°C and 70% if it's >= 70°C. Any temperature between those 2 steps use linear interpolation.

For zone 2, it'll use the average temperature of `disk1` and `disk2` to determine the fan speed.

Normally, you want at least 2 steps so that you'll have a min and max fan speed. You can add more if you want to customize your fan curve more. For example, if you don't want your fans to ramp up quickly, you could do something like this:

```toml
steps = [
    { temp = 30, dcycle = 30 },
    { temp = 50, dcycle = 40 },
    { temp = 80, dcycle = 100 },
]
```

That'd give you a slower ramp-up until it hits 50°C. This is how it looks as a graph:

![image](https://user-images.githubusercontent.com/646253/155900512-7f02341a-7af3-478f-b518-8d605ce0ecd0.png)

**Comment by rajil** [comment]
Thanks for the explanation.
